import {
  AlertTriangle,
  Bot,
  CheckCircle2,
  Clock,
  FileText,
  ShieldCheck,
} from "lucide-react";

export default function CaseDetailsPage() {
  const timeline = [
    "Case created by Intake Agent",
    "Document parsed by Document Agent",
    "Risk score generated by Risk Agent",
    "Duplicate invoice detected by Exception Agent",
    "Human review requested",
    "Resolution pending approval",
  ];

  return (
    <main className="min-h-screen bg-[#020617] p-8 text-white">
      <div className="mb-8">
        <p className="text-sm font-semibold text-blue-400">CASE-001</p>
        <h1 className="mt-2 text-4xl font-black">
          Invoice Exception Review
        </h1>
        <p className="mt-2 text-slate-400">
          Full case intelligence view with risk explanation, agent actions,
          human approval, and audit trail.
        </p>
      </div>

      <section className="grid gap-6 lg:grid-cols-3">
        <div className="glass-card rounded-3xl p-6">
          <AlertTriangle className="mb-4 text-red-400" />
          <h2 className="text-xl font-bold">Risk Score</h2>
          <p className="mt-3 text-5xl font-black">86</p>
          <p className="mt-2 text-red-300">High Risk</p>
        </div>

        <div className="glass-card rounded-3xl p-6">
          <Clock className="mb-4 text-yellow-400" />
          <h2 className="text-xl font-bold">Status</h2>
          <p className="mt-3 text-3xl font-black">Human Review</p>
          <p className="mt-2 text-slate-400">Manual approval required.</p>
        </div>

        <div className="glass-card rounded-3xl p-6">
          <ShieldCheck className="mb-4 text-blue-400" />
          <h2 className="text-xl font-bold">Recommendation</h2>
          <p className="mt-3 text-3xl font-black">Review</p>
          <p className="mt-2 text-slate-400">Do not auto-approve this case.</p>
        </div>
      </section>

      <section className="mt-8 grid gap-6 xl:grid-cols-2">
        <div className="glass-card rounded-3xl p-6">
          <div className="mb-6 flex items-center gap-3">
            <Bot className="text-blue-400" />
            <h2 className="text-2xl font-bold">AI Explanation</h2>
          </div>

          <div className="space-y-4 text-slate-300">
            <p>
              This case was marked as high risk because the invoice amount is
              unusually large, the invoice ID appears similar to a previous
              transaction, and required supporting documents are missing.
            </p>

            <ul className="list-disc space-y-2 pl-6">
              <li>Duplicate invoice pattern detected.</li>
              <li>Amount exceeds normal approval threshold.</li>
              <li>Human approval is required before resolution.</li>
            </ul>
          </div>
        </div>

        <div className="glass-card rounded-3xl p-6">
          <div className="mb-6 flex items-center gap-3">
            <FileText className="text-purple-400" />
            <h2 className="text-2xl font-bold">Case Data</h2>
          </div>

          <div className="space-y-4 text-sm">
            <div className="flex justify-between border-b border-slate-800 pb-3">
              <span className="text-slate-400">Invoice ID</span>
              <span>INV-001</span>
            </div>
            <div className="flex justify-between border-b border-slate-800 pb-3">
              <span className="text-slate-400">Customer</span>
              <span>Acme Corporation</span>
            </div>
            <div className="flex justify-between border-b border-slate-800 pb-3">
              <span className="text-slate-400">Amount</span>
              <span>$25,000</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Assigned Agent</span>
              <span>Case Brain Agent</span>
            </div>
          </div>
        </div>
      </section>

      <section className="mt-8 glass-card rounded-3xl p-6">
        <div className="mb-6 flex items-center gap-3">
          <CheckCircle2 className="text-emerald-400" />
          <h2 className="text-2xl font-bold">Case Timeline</h2>
        </div>

        <div className="space-y-4">
          {timeline.map((event, index) => (
            <div
              key={event}
              className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4"
            >
              <p className="text-sm text-slate-400">Step {index + 1}</p>
              <p className="mt-1 font-semibold">{event}</p>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}