export default function AuditPage() {

  return (
    <main className="min-h-screen bg-[#020617] p-8 text-white">

      <h1 className="text-4xl font-bold mb-8">
        Audit Logs
      </h1>

      <div className="space-y-4">

        <div className="glass-card rounded-2xl p-5">
          Risk generated by Risk Agent
        </div>

        <div className="glass-card rounded-2xl p-5">
          Human review triggered
        </div>

      </div>

    </main>
  );

}